version: '3.1'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 54.205.80.238:8000 --workers 4 "app.app:app()"
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - flask-app

networks:
  my-network:
